name = "uuid-queue"
main = "src/index.ts"
compatibility_date = "2022-10-29"
route = "queue.uuid.rocks/*"
usage_model = "unbound"

[[r2_buckets]]
binding = 'UUIDS' # <~ valid JavaScript variable name
bucket_name = 'uuids'

# Worker defines a binding, named "QUEUE", which gives it a capability
# to send messages to a Queue, named "my-queue".
[[queues.producers]]
  queue = "uuid-queue"
  binding = "QUEUE"

# Worker also receives messages from the Queue, named "my-queue".
[[queues.consumers]]
  queue = "uuid-queue"
  max_batch_size = 100   # Max messages per batch
  max_batch_timeout = 30 # Max seconds to wait before batch is full
  max_retries = 3       # Max retries per batch

[triggers]
crons = ["10 * * * *"]
